version: "3"
services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitcont
    ports:
      - '5672:5672'

  products:
    build:
      dockerfile: Dockerfile
      context: ./ProductService
    container_name: ProductService
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/ProductService/node_modules

    env_file:
      - ./ProductService/.env.dev
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./ShoppingService
    container_name: shopping
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/ShoppingService/node_modules
    env_file:
      - ./ShoppingService/.env.dev
  customer:
    build:
      dockerfile: Dockerfile
      context: ./CustomerService
    container_name: customer
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/CustomerService/node_modules
    env_file:
      - ./CustomerService/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80